### PR TITLE
Add ghactions from sf

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by luukvdmeer** [comment]
I am definitely not an expert on GH actions, but was wondering: is it needed for the sfnetworks repo to include system dependency checks of sf's system dependencies? I mean, `sf` is an dependency of `sfnetworks`, so indirectly `sfnetworks` of course has `gdal` and friends as system dependencies, but these are not direct dependencies of the package. I am just wondering if we are not overly complicating ourselves if we explicitly include indirect dependencies in the checks (which would also raise the question if we then should not also do the same for the system dependencies of `tidygraph`/`igraph`).

But as said, this remark comes from a complete non-expert in GH actions! ;)

**Comment by Robinlovelace** [comment]
Those dependencies are in there to make the checks pass. We need to sf add system dependencies before installing any package that uses sf. I'm a fan of simplicity and there may be ways to further simplify the .yaml code but I think this is currently close to the simplest we can get it.

**Comment by Robinlovelace** [comment]
Quick question for @tiennebr, who pioneered the use of GH Actions in sf, is there a simpler way of getting sf dependencies installed? Here's the currently (passing) setup I'm suggesting for this package: https://github.com/luukvdmeer/sfnetworks/blob/ea43e21ae6fe54f46a700568d5255b47ab7f207c/.github/workflows/R-CMD-check.yaml

**Comment by etiennebr** [comment]
Depending on the dependencies you need, you could use the precompiled binaries. It seems to work for, e.g., [`geotidy`](https://github.com/etiennebr/geotidy/blob/master/.github/workflows/R-CMD-check.yaml) (works for windows, mac and linux). 

If this fails, then I think using `sf` actions is the way to go for now. I'd like to explore an actions repo to install dependencies, such as: 
``` yaml
- uses: r-spatial/actions/setup-gdal@master  # doesn't exist yet :(
```
Note that I'm working on the `sf` actions, so it already evolved from what you just merged (@ateucher improved the mac dependencies). For that reason, having a central repo for packages to pull actions would be the best solution (as you suggested initially). But for now, you'll have to keep an eye on the `sf` actions if the binaries don't work for you.

**Comment by Robinlovelace** [comment]
Great, many thanks @etiennebr, that is really useful to know. For now the fact that it passes is the main thing. If it starts failing, or if I see activity in https://github.com/r-spatial/sf/issues/1309 , we can always revisit. Hugely appreciative of the work you're doing on automated tests and continuous integration for key geographic R packages.

**Pull request merged**
