### PR TITLE
Bench

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Heads-up @luukvdmeer and all, this PR adds some basic benchmarks to track performance. If it goes to plan, GH Actions should report benchmark runtime for every push and report results like this: https://github.com/r-lib/bench/runs/777595294?check_suite_focus=true#step:7:8

I used the https://github.com/r-lib/bench repo as a bit of a template. Hope it works, yielded interesting results already for #6.

**Comment by luukvdmeer** [comment]
Great, thanks @Robinlovelace ! Any idea where the error message of the check is coming from? It seems to fail at line 1 already with `An action could not be found at the URI 'https://api.github.com/repos/actions/checkout/tarball/develop'`

**Comment by Robinlovelace** [comment]
Seems it was trying to checkout a non-existent branch. Trying with `master` again...

**Comment by Robinlovelace** [comment]
Heads-up @luukvdmeer it seems to be passing now :tada:

**Comment by Robinlovelace** [comment]
What do you reckon @luukvdmeer ?

**Comment by luukvdmeer** [comment]
Sorry I took sime time. Busy working life! I am happy it passes. Merged to develop.

**Comment by Robinlovelace** [comment]
Thanks @luukvdmeer I'm impressed and think that, assuming the `st_length()` calculation isn't to blame, sfnetworks seems faster than `stplanr`. Yet to be proven. Next step on this may be a vignette on performance.

**Pull request merged**
